-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Oct 25, 2025 at 01:56 PM
-- Server version: 10.6.16-MariaDB-cll-lve
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `oqqcvjzs_ati`
--

-- --------------------------------------------------------

--
-- Table structure for table `about_page_content`
--

CREATE TABLE `about_page_content` (
  `id` int(11) NOT NULL,
  `banner_title` varchar(255) NOT NULL,
  `banner_subtitle` varchar(255) DEFAULT NULL,
  `banner_image_url` varchar(255) DEFAULT NULL,
  `welcome_heading` varchar(255) NOT NULL,
  `welcome_text` text DEFAULT NULL,
  `welcome_image_url` varchar(255) DEFAULT NULL,
  `principles_heading` varchar(255) DEFAULT NULL,
  `vision_icon` varchar(50) DEFAULT NULL,
  `vision_title` varchar(255) DEFAULT NULL,
  `vision_text` text DEFAULT NULL,
  `mission_icon` varchar(50) DEFAULT NULL,
  `mission_title` varchar(255) DEFAULT NULL,
  `mission_text` text DEFAULT NULL,
  `choose_us_heading` varchar(255) DEFAULT NULL,
  `choose_us_text` text DEFAULT NULL,
  `last_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `about_page_content`
--

INSERT INTO `about_page_content` (`id`, `banner_title`, `banner_subtitle`, `banner_image_url`, `welcome_heading`, `welcome_text`, `welcome_image_url`, `principles_heading`, `vision_icon`, `vision_title`, `vision_text`, `mission_icon`, `mission_title`, `mission_text`, `choose_us_heading`, `choose_us_text`, `last_updated`) VALUES
(1, 'Learn. Grow Succeed', 'Join The Advanced Technological Institute in Galle', 'uploads/about_page/1760435259_unnamed.jpg', 'Welcome to ATI Galle', 'Welcome to the Galle Advanced Technological Institute your launchpad to professional excellence. This is where raw talent meets cutting edge technology.', 'uploads/about_page/1760435259_Cb5MxgeWIAA5_dw.jpeg', 'Vision & Mission', 'fas fa-eye', 'Our Vision', 'To cultivate a transformative learning environment that empowers every student to become a highly skilled, ethical, and future-proof leader in technology and management.', 'fas fa-bullseye', 'Our Mission', 'To empower every student with practical expertise and advanced technological knowledge, transforming them into confident, ethical leaders prepared to excel in the competitive global workforce.', 'Why Us', NULL, '2025-10-15 03:58:53');

-- --------------------------------------------------------

--
-- Table structure for table `albums`
--

CREATE TABLE `albums` (
  `AlbumId` varchar(50) NOT NULL COMMENT 'Unique Album ID, e.g., generated by uniqid("album_")',
  `album_name` varchar(255) NOT NULL COMMENT 'Name of the album, e.g., "Event XYZ Photos"',
  `created_at` timestamp NULL DEFAULT current_timestamp() COMMENT 'Timestamp of album creation'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `albums`
--

INSERT INTO `albums` (`AlbumId`, `album_name`, `created_at`) VALUES
('album_68ede50c141d8', '\'Introva\' Success! IT Students Blend Gaming Excitement with Future-Forward Innovation Album', '2025-10-14 05:52:12'),
('album_68f217a321159', 'Labuduwa ATI Engineering Department Organizes \'INVENTEX\' Open to Students Nationwide Album', '2025-10-17 10:17:07'),
('album_68f21b8e0923f', 'Labuduwa ATI IT Team Steals the Spotlight at Engineering\'s \'INVENTEX\' Exhibition Album', '2025-10-17 10:33:50'),
('album_68f524882d6d9', 'Beyond the Screen: Labuduwa ATI IT Students Celebrate Teachers with \'Guru Abinandana\' and Green Initiative Album', '2025-10-19 17:48:56');

-- --------------------------------------------------------

--
-- Table structure for table `album_images`
--

CREATE TABLE `album_images` (
  `image_id` int(11) NOT NULL COMMENT 'Auto-incrementing unique ID for each image entry',
  `AlbumId` varchar(50) NOT NULL COMMENT 'Foreign key referencing the album this image belongs to',
  `image_path` varchar(512) NOT NULL COMMENT 'Path to the image file (e.g., uploads/albums/AlbumId/image.jpg)',
  `uploaded_at` timestamp NULL DEFAULT current_timestamp() COMMENT 'Timestamp of image upload'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `album_images`
--

INSERT INTO `album_images` (`image_id`, `AlbumId`, `image_path`, `uploaded_at`) VALUES
(1, 'album_68ede50c141d8', 'uploads/albums/album_68ede50c141d8/1760421132_68ede50c1507a_473993858_122186449808161373_4737055112137186758_n.jpg', '2025-10-14 05:52:12'),
(2, 'album_68f217a321159', 'uploads/albums/album_68f217a321159/1760696227_68f217a3216d1_WhatsApp_Image_2025-05-21_at_06.05.04_40ddf6b8.jpg', '2025-10-17 10:17:07'),
(3, 'album_68f21b8e0923f', 'uploads/albums/album_68f21b8e0923f/1760697230_68f21b8e0987b_512441687_1170234648467455_4874232720881910038_n.jpg', '2025-10-17 10:33:50'),
(4, 'album_68f524882d6d9', 'uploads/albums/album_68f524882d6d9/1760896136_68f524882dbf6_1760695045_retouch_2025101322274845.jpg', '2025-10-19 17:48:56');

-- --------------------------------------------------------

--
-- Table structure for table `authors`
--

CREATE TABLE `authors` (
  `author_id` int(11) NOT NULL,
  `author_name` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `authors`
--

INSERT INTO `authors` (`author_id`, `author_name`) VALUES
(1, 'Anes Mohamed'),
(2, 'Gunaseelan Gunasegaran'),
(3, 'Daminda Herath'),
(4, 'Priyanka Thirumugam'),
(5, 'Shehan Amarasooriya'),
(6, 'Dr. Aruna Perera'),
(7, 'Nimali Silva'),
(8, 'Saman Kumara'),
(9, 'Dr. Evelyn Reed'),
(10, 'Ben Carter'),
(11, 'ben'),
(13, 'fg'),
(14, 'fg'),
(15, 'fg'),
(16, 'TW'),
(17, 'TW');

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `category_id` int(11) NOT NULL,
  `category_name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`category_id`, `category_name`) VALUES
(1, 'Scientific Research'),
(2, 'Technology & IoT'),
(3, 'Management Studies'),
(4, 'HNDIT');

-- --------------------------------------------------------

--
-- Table structure for table `choose_us_points`
--

CREATE TABLE `choose_us_points` (
  `id` int(11) NOT NULL,
  `icon_class` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `display_order` int(11) DEFAULT 0,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `choose_us_points`
--

INSERT INTO `choose_us_points` (`id`, `icon_class`, `title`, `description`, `display_order`, `is_active`, `created_at`) VALUES
(1, 'fas fa-eye', 'The Practical Edge', 'We don\'t just teach theory; we build expertise. Our curriculum is crafted in partnership with industry leaders to ensure you master the exact, in-demand technical skills the market needs today and tomorrow. You won\'t just earn a diploma you\'ll leave with a portfolio of practical achievements and the confidence to lead any project.', 1, 1, '2025-10-14 05:13:56'),
(4, 'fas fa-eye', 'The Visionary Advantage', 'Stop worrying about outdated qualifications. ATI Galle is focused on future-proofing your potential. We invest heavily in cutting-edge labs and facilities that reflect the modern technological workplace. Here, you learn the foundational science alongside the next big innovation, ensuring your knowledge is always relevant.', 2, 1, '2025-10-14 09:54:52');

-- --------------------------------------------------------

--
-- Table structure for table `course`
--

CREATE TABLE `course` (
  `cid` varchar(12) NOT NULL,
  `cname` varchar(255) DEFAULT NULL,
  `ctext` text DEFAULT NULL,
  `cimg` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `status` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`cid`, `cname`, `ctext`, `cimg`, `created_at`, `updated_at`, `status`) VALUES
('HND_ENGLISH', 'Higher National Diploma in English(HND in English) ', '', 'uploads/course_images/course_68f4b8b64e90a6.38016306.png', '2025-10-14 01:02:27', '2025-10-19 06:08:54', 1),
('HNDA', 'Higher National Diploma in Accountancy(HNDA)', '', 'uploads/course_images/course_68f4b8a76ecd01.51560940.png', '2025-10-14 01:00:29', '2025-10-19 06:08:39', 1),
('HNDBA', 'Higher National Diploma in Business Administration(HNDBA)', '', 'uploads/course_images/course_68f4b88d7aab39.02941017.png', '2025-10-14 01:00:48', '2025-10-19 06:08:13', 1),
('HNDCE', 'Higher National Diploma in Engineering (Civil)', '', 'uploads/course_images/course_68f4b8dfeaf765.64556813.png', '2025-10-14 00:59:04', '2025-10-19 06:09:35', 1),
('HNDEE', 'Higher National Diploma in Engineering (Electrical)', '', 'uploads/course_images/course_68f4b8cfa4c1d0.22379265.png', '2025-10-14 00:57:58', '2025-10-19 06:09:19', 1),
('HNDIT', 'Higher National Diploma in Information  Technology', '<p>sample test phara&nbsp;</p>\r\n<p>sample test phara&nbsp;</p>\r\n<p>sample test phara&nbsp;</p>\r\n<p>sample test phara&nbsp;</p>\r\n<p>sample test phara&nbsp;</p>', 'uploads/course_images/course_68f4af198855c9.13037338.png', '2025-10-14 00:53:18', '2025-10-19 05:42:47', 1),
('HNDM', 'Higher National Diploma in Management(HNDM)', '', 'uploads/course_images/course_68f4b89d4c0874.28861057.png', '2025-10-14 01:02:59', '2025-10-19 06:08:29', 1),
('HNDME', 'Higher National Diploma in Engineering (Mechanical)', '', 'uploads/course_images/course_68f4b47a89a9f1.47021260.png', '2025-10-14 00:55:56', '2025-10-19 05:50:50', 1),
('HNDQS', 'Higher National Diploma in Quantity Survey (HNDQS)', '', 'uploads/course_images/course_68f4b8c3299388.90461092.png', '2025-10-14 01:00:06', '2025-10-19 06:09:07', 1),
('HNDT', 'Higher National Diploma in Technology (Agriculture) ', '', 'uploads/course_images/course_68f4b882be18d9.86776014.png', '2025-10-14 01:03:22', '2025-10-19 06:08:02', 1),
('HNDTHM', 'Higher National Diploma in Tourism and Hospitality Management (HNDTHM)', '', '', '2025-10-14 01:03:44', '2025-10-14 01:03:44', 1);

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

CREATE TABLE `events` (
  `eid` varchar(255) NOT NULL COMMENT 'Event ID, as used in your PHP code (e.g., user-defined or unique string)',
  `etitle` varchar(255) NOT NULL COMMENT 'Event Title',
  `etext` text DEFAULT NULL COMMENT 'Event Description, can store HTML content from TinyMCE',
  `etag` text DEFAULT NULL COMMENT 'SEO Tags, comma-separated or other format',
  `AlbumId` varchar(50) DEFAULT NULL COMMENT 'Foreign key referencing the associated album in the albums table',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Event status: 1 for Active, 0 for Inactive',
  `created_by_cid` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp() COMMENT 'Timestamp of event creation',
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Timestamp of last event update'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`eid`, `etitle`, `etext`, `etag`, `AlbumId`, `status`, `created_by_cid`, `created_at`, `updated_at`) VALUES
('evt_68ede35fd3573', '\'Introva\' Success! IT Students Blend Gaming Excitement with Future-Forward Innovation', '<p>The IT Department\'s successful \'Introva\' competition wrapped up, showcasing brilliant student projects and thrilling e-sports. We were honored to host <strong>Mr. Damitha, Provincial Director of the Southern Province Irrigation Department</strong>, as our Chief Guest. The event highlighted the technical and organizational excellence of our students.</p>', 'Introva, IT Department, ATI Galle, Gaming Competition, Project Showcase', 'album_68ede50c141d8', 1, 'SAdmin', '2025-10-14 05:52:12', '2025-10-14 05:53:38'),
('evt_68f2148427141', 'Labuduwa ATI Engineering Department Organizes \'INVENTEX\' Open to Students Nationwide', '<p>The Labuduwa ATI Engineering Department launched a powerful surge of innovation with its flagship exhibition, <strong>\'INVENTEX\'</strong>, showcasing the technical brilliance of its students through practical, future-focused projects. This year, the event broke boundaries by welcoming a collaborative team from the Information Technology (IT)<strong> </strong>Department, whose integrated software solutions enhanced the hardware designs, creating truly smart systems. In a generous move to fuel nationwide interest, the exhibition offered free entry to all, inviting school and university students from across Sri Lanka to step into a world of invention, cementing INVENTEX as a vital hub for technological inspiration and cross-disciplinary synergy.</p>', 'INVENTEX, Labuduwa ATI, Engineering Exhibition', 'album_68f217a321159', 1, 'SAdmin', '2025-10-17 10:17:07', '2025-10-17 10:17:07'),
('evt_68f217a322ebd', 'Labuduwa ATI IT Team Steals the Spotlight at Engineering\'s \'INVENTEX\' Exhibition', '<p>The <strong>Engineering Department\'s</strong> grand exhibition, <strong>\'INVENTEX\'</strong>, at Labuduwa ATI, was significantly enhanced by the participation of the <strong>Information Technology (IT) Department</strong>. A dedicated team of IT students joined the showcase, moving beyond traditional engineering displays to present key digital innovations. Their focus was on vital, practical projects: they proudly showcased the officially managed Galle ATI website and a comprehensive <strong>career guidance website</strong>. This contribution highlighted the essential role of IT in institutional advancement and student future planning, cementing INVENTEX as a hub not just for engineering prowess, but for cross-departmental synergy and real-world digital development at Labuduwa ATI.</p>', 'INVENTEX, Labuduwa ATI IT, Engineering Exhibition, IT Project Showcase, HNDIT Innovation, Cross-Departmental Collaboration', 'album_68f21b8e0923f', 1, 'SAdmin', '2025-10-17 10:33:50', '2025-10-25 04:15:10'),
('evt_68f524450ff83', 'Beyond the Screen: Labuduwa ATI IT Students Celebrate Teachers with \'Guru Abinandana\' and Green Initiative', '<div class=\"article-text\">\r\n<p>The Information Technology Department of Labuduwa ATI recently celebrated Teacher\'s Day with a memorable event titled&nbsp;<strong>\"Guru Abinandana\"</strong>. Students showcased their diverse talents through vibrant cultural performances to express heartfelt gratitude for their lecturers\' dedication. The tribute was followed by a meaningful Green Initiative, where students and faculty collaborated on a plantation program on campus. This dual event successfully blended artistic appreciation with environmental responsibility, reinforcing the strong bond and shared commitment to growth within the Labuduwa ATI community.</p>\r\n</div>', 'HNDIT,', 'album_68f524882d6d9', 1, 'SAdmin', '2025-10-19 17:48:56', '2025-10-19 17:48:56');

-- --------------------------------------------------------

--
-- Table structure for table `login_logs`
--

CREATE TABLE `login_logs` (
  `id` int(11) NOT NULL,
  `user_cid` varchar(100) DEFAULT NULL COMMENT 'Corresponds to admin.cid or username',
  `login_time` timestamp NOT NULL DEFAULT current_timestamp(),
  `ip_address` varchar(45) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL COMMENT 'e.g., City, Country',
  `user_agent` text DEFAULT NULL COMMENT 'Browser and OS info',
  `status` varchar(20) NOT NULL DEFAULT 'success' COMMENT 'e.g., success, failed'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `login_logs`
--

INSERT INTO `login_logs` (`id`, `user_cid`, `login_time`, `ip_address`, `location`, `user_agent`, `status`) VALUES
(1, 'mano13', '2025-10-17 07:48:44', '112.134.158.193', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(2, 'mano14', '2025-10-17 09:24:59', '112.134.158.193', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(3, 'yahodhara1', '2025-10-17 09:32:40', '112.134.158.193', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'failed'),
(4, 'yahodhara1', '2025-10-17 09:32:51', '112.134.158.193', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'failed'),
(5, 'yashodhara1', '2025-10-17 09:33:23', '112.134.158.193', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(6, 'vihanga', '2025-10-17 17:49:58', '123.231.127.19', 'Kandy, Central Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(7, 'vihanga', '2025-10-18 03:53:58', '51.159.77.202', 'Paris, ÃŽle-de-France, France', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(8, 'vihanga', '2025-10-18 07:30:27', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(9, 'vihanga', '2025-10-18 07:43:37', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(10, 'mano11', '2025-10-18 07:44:15', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'failed'),
(11, 'mano13', '2025-10-18 07:44:21', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(12, 'mano14', '2025-10-18 07:49:09', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(13, 'mano14', '2025-10-18 07:52:29', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(14, 'mano14', '2025-10-18 08:00:12', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(15, 'nipuni', '2025-10-18 08:22:56', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(16, 'nipuni', '2025-10-18 08:23:25', '111.223.185.24', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(17, 'UN nipuni', '2025-10-18 14:37:57', '175.157.252.140', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(18, 'nipuni', '2025-10-18 14:38:13', '175.157.252.140', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(19, 'nipuni', '2025-10-18 14:39:02', '175.157.252.140', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(20, 'nipuni', '2025-10-18 14:40:04', '175.157.252.140', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(21, 'nipuni', '2025-10-19 02:24:25', '108.181.21.151', 'Los Angeles, California, United States', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(22, 'vihanga', '2025-10-19 03:18:00', '108.181.34.151', 'Los Angeles, California, United States', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(23, 'vihanga', '2025-10-19 03:19:50', '111.223.183.89', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Mobile Safari/537.36', 'success'),
(24, 'nipuni', '2025-10-19 07:13:52', '175.157.224.4', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(25, 'nipuni', '2025-10-19 07:23:53', '175.157.224.4', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(26, 'vihanga', '2025-10-19 07:40:20', '175.157.136.233', 'Kadawatha, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(27, 'mano14', '2025-10-19 07:50:19', '175.157.136.233', 'Kadawatha, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(28, 'vihanga', '2025-10-19 17:47:39', '123.231.120.97', 'Kandy, Central Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(29, 'nipuni', '2025-10-21 03:56:38', '175.157.99.236', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success'),
(30, 'Super Admin', '2025-10-23 14:15:44', '112.134.105.111', 'Angunakolapelessa, Southern Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'failed'),
(31, 'Super Admin', '2025-10-23 14:16:19', '112.134.105.111', 'Angunakolapelessa, Southern Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'failed'),
(32, 'vihanga', '2025-10-23 17:20:04', '103.21.165.238', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(33, 'vihanga', '2025-10-24 08:58:20', '112.134.158.32', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(34, 'mano11', '2025-10-24 10:32:34', '112.134.153.225', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'failed'),
(35, 'mano13', '2025-10-24 10:32:40', '112.134.153.225', 'Panadura, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36', 'success'),
(36, 'Test@123123456', '2025-10-25 05:16:07', '175.157.63.82', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(37, 'Test@123', '2025-10-25 05:16:27', '175.157.63.82', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(38, 'Test@123', '2025-10-25 05:16:39', '175.157.63.82', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(39, 'Test@123', '2025-10-25 05:16:58', '175.157.63.82', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(40, 'Super Admin', '2025-10-25 05:18:37', '175.157.63.82', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'failed'),
(41, 'nipuni', '2025-10-25 05:19:01', '175.157.63.82', 'Colombo, Western Province, Sri Lanka', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0', 'success');

-- --------------------------------------------------------

--
-- Table structure for table `modules`
--

CREATE TABLE `modules` (
  `module_code` varchar(10) NOT NULL,
  `module_title` varchar(255) DEFAULT NULL,
  `module_type` varchar(20) DEFAULT NULL,
  `credits` int(11) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `semester` int(11) DEFAULT NULL,
  `cid` varchar(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `modules`
--

INSERT INTO `modules` (`module_code`, `module_title`, `module_type`, `credits`, `status`, `year`, `semester`, `cid`) VALUES
('EN1101', 'Engineering Mathematics I', 'GPA', 3, '1', 1, 1, 'HNDME'),
('EN1102', 'Introduction to Fluid Mechanics', 'GPA', 2, '1', 1, 1, 'HNDME'),
('EN1103', 'English and Communication Skills I', 'GPA', 2, '1', 1, 1, 'HNDME'),
('EN1104', 'Programming Concepts', 'GPA', 3, '1', 1, 1, 'HNDME'),
('EN1105', 'Electrical and Electronics Engineering Fundamentals I', 'GPA', 3, '1', 1, 1, 'HNDME'),
('EN1106', 'Workshop Engineering', 'GPA', 2, '1', 1, 1, 'HNDME'),
('EN1107', 'Engineering Drawing', 'GPA', 3, '1', 1, 1, 'HNDME'),
('EN1208', 'Engineering Mathematics II', 'GPA', 3, '1', 1, 2, 'HNDME'),
('EN1209', 'Introduction to Thermodynamics', 'GPA', 2, '1', 1, 2, 'HNDME'),
('EN1210', 'English and Communication Skills II', 'GPA', 2, '1', 1, 2, 'HNDME'),
('EN1211', 'Computer Technology and Networking', 'GPA', 3, '1', 1, 2, 'HNDME'),
('EN1212', 'Electrical and Electronics Engineering Fundamentals II', 'GPA', 2, '1', 1, 2, 'HNDME'),
('EN1213', 'Properties of Engineering Materials', 'GPA', 2, '1', 1, 2, 'HNDME'),
('EN1214', 'Engineering mechanics', 'GPA', 3, '1', 1, 2, 'HNDME'),
('EN1215', 'Human Values and Professional Ethics', 'NGPA', 1, '1', 1, 2, 'HNDME'),
('HNDIT1012', 'Visual Application Programming', 'GPA', 4, '1', 1, 1, 'HNDIT'),
('HNDIT1022', 'Web Design', 'GPA', 4, '1', 1, 1, 'HNDIT'),
('HNDIT1032', 'Computer and Network System', 'GPA', 3, '1', 1, 1, 'HNDIT'),
('HNDIT1042', 'Information Management and Information System', 'GPA', 4, '1', 1, 1, 'HNDIT'),
('HNDIT1052', 'ICT Project (Individual)', 'GPA', 3, '1', 1, 1, 'HNDIT'),
('HNDIT1062', 'Communication Skills', 'GPA', 2, '1', 1, 1, 'HNDIT'),
('HNDIT2012', 'Fundamentals of Programming', 'GPA', 4, '1', 1, 2, 'HNDIT'),
('HNDIT2022', 'Software Development', 'GPA', 3, '1', 1, 2, 'HNDIT'),
('HNDIT2032', 'System Analysis and Design', 'GPA', 3, '1', 1, 2, 'HNDIT'),
('HNDIT2042', 'Data Communication and Computer Networks', 'GPA', 3, '1', 1, 2, 'HNDIT'),
('HNDIT2052', 'Principles of  User Interface Design', 'GPA', 3, '1', 1, 2, 'HNDIT'),
('HNDIT2062', 'ICT Project(Group)', 'GPA', 2, '1', 1, 2, 'HNDIT'),
('HNDIT2072', 'Technical Writing', 'GPA', 2, '1', 1, 2, 'HNDIT'),
('HNDIT2082', 'Human Value & Professional Ethics', 'NGPA', 1, '1', 1, 2, 'HNDIT'),
('HNDIT2323', 'web design3', 'GPA', 3, '1', 2, 1, 'HNDA'),
('HNDIT23235', 'web design3', 'GPA', 3, '1', 2, 1, 'HNDA'),
('HNDIT3012', 'Object Oriented Programming', 'GPA', 4, '1', 2, 1, 'HNDIT'),
('HNDIT3022', 'Web Programming', 'GPA', 4, '1', 2, 1, 'HNDIT'),
('HNDIT3032', 'Data Structures and Algorithms', 'GPA', 2, '1', 2, 1, 'HNDIT'),
('HNDIT3042', 'Database Management System', 'GPA', 3, '1', 2, 1, 'HNDIT'),
('HNDIT3052', 'Operating System', 'GPA', 2, '1', 2, 1, 'HNDIT'),
('HNDIT3062', 'Information and Computer Security', 'GPA', 2, '1', 2, 1, 'HNDIT'),
('HNDIT3072', 'Statistics for IT', 'GPA', 3, '1', 2, 1, 'HNDIT'),
('HNDIT4012', 'Software Engineering', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('HNDIT4022', 'Software Quality Assurance', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('HNDIT4032', 'IT Project Management', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('HNDIT4042', 'Professional World', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('HNDIT4052', 'Programming Individual Project', 'GPA', 2, '1', 2, 2, 'HNDIT'),
('HNDIT4212', 'Machine Learning (ELECTIVE)', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('HNDIT4222', 'Business Analysis Practice(ELECTIVE)', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('HNDIT4232', 'Enterprise Architecture', 'GPA', 3, '1', 2, 2, 'HNDIT'),
('ME2116', 'Advanced Engineering Mathematics', 'GPA', 3, '1', 2, 1, 'HNDME'),
('ME2117', 'Dynamics of Mechanical Systems', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2118', 'Engineering Fluid Mechanics I', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2119', 'Engineering Thermodynamics I', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2120', 'Strength of Materials I', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2121', 'Advanced Engineering Graphics I', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2122', 'Manufacturing Technology I', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2123', 'Electrical Machines and Drives I', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2124', 'Automobile Technology', 'GPA', 2, '1', 2, 1, 'HNDME'),
('ME2226', 'Engineering Fluid Mechanics II', 'GPA', 2, '1', 2, 2, 'HNDME'),
('ME2227', 'Engineering Thermodynamics II', 'GPA', 3, '1', 2, 2, 'HNDME'),
('ME2228', 'Strength of Materials II', 'GPA', 2, '1', 2, 2, 'HNDME'),
('ME2229', 'Advanced Engineering Graphics II', 'GPA', 2, '1', 2, 2, 'HNDME'),
('ME2230', 'Manufacturing Technology II', 'GPA', 2, '1', 2, 2, 'HNDME'),
('ME2231', 'Electrical Machines and Drives II', 'GPA', 2, '1', 2, 2, 'HNDME'),
('ME2232', 'Production Technology I (ELECTIVE)', 'GPA', 2, '1', 2, 2, 'HNDME'),
('ME2233', 'Refrigeration and Air Conditioning I', 'GPA', 2, '1', 2, 2, 'HNDME');

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `nid` int(11) NOT NULL,
  `ntitle` varchar(255) NOT NULL,
  `ntag` text DEFAULT NULL,
  `cid` varchar(12) DEFAULT NULL,
  `ntext` text DEFAULT NULL,
  `nimg` varchar(255) DEFAULT NULL,
  `count` int(11) DEFAULT 0,
  `status` tinyint(4) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`nid`, `ntitle`, `ntag`, `cid`, `ntext`, `nimg`, `count`, `status`, `created_at`, `updated_at`) VALUES
(1, 'A New Chapter Begins: Mr. Thamra Waidyarathna Assumes Directorship at ATI Galle', 'Thamra Waidyarathna, Director, ATI Galle, New Director, SLIATE, Labuduwa, Advanced Technological Institute', '', '<p>We are immensely proud and excited to announce that Mr. Thamra Waidyarathna has formally assumed duties as the new Director of the Galle Labuduwa Advanced Technological Institute.</p>\r\n<p>With a proven track record in educational leadership and strategic vision, Mr. Waidyarathna brings a fresh dynamic to our esteemed institution. His leadership marks the beginning of an exciting chapter focused on elevating academic standards, fostering cutting-edge research, and empowering the next generation of skilled professionals.</p>\r\n<p>We look forward to achieving new milestones in technical education under his guidance. Join us in extending a warm welcome to Director Thamra Waidyarathna!</p>', 'uploads/news_images/1760435799_WhatsApp_Image_2025-10-14_at_9.20.33_AM__2_.jpeg', 7, 1, '2025-10-14 05:30:57', '2025-10-25 10:54:27'),
(2, 'Beyond the Screen: Labuduwa ATI IT Students Celebrate Teachers with \'Guru Abinandana\' and Green Initiative', 'Labuduwa ATI, IT Department, Teacher\'s Day, Guru Abinandana, Student Talents, Tree Planting, Green Initiative, SLIATE Galle, HNDIT', 'HNDIT', '<p>The Information Technology Department of Labuduwa ATI recently celebrated Teacher\'s Day with a memorable event titled <strong>\"Guru Abinandana\"</strong>. Students showcased their diverse talents through vibrant cultural performances to express heartfelt gratitude for their lecturers\' dedication. The tribute was followed by a meaningful Green Initiative, where students and faculty collaborated on a plantation program on campus. This dual event successfully blended artistic appreciation with environmental responsibility, reinforcing the strong bond and shared commitment to growth within the Labuduwa ATI community.</p>', 'uploads/news_images/1760695045_retouch_2025101322274845.jpg', 11, 1, '2025-10-17 09:56:13', '2025-10-25 10:51:36');

-- --------------------------------------------------------

--
-- Table structure for table `notifications`
--

CREATE TABLE `notifications` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `message` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `is_read` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `publications`
--

CREATE TABLE `publications` (
  `publication_id` int(11) NOT NULL,
  `title` text NOT NULL,
  `conference_details` text DEFAULT NULL,
  `publication_date` date NOT NULL,
  `category_id` int(11) NOT NULL,
  `abstract` text DEFAULT NULL,
  `full_text_url` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `publications`
--

INSERT INTO `publications` (`publication_id`, `title`, `conference_details`, `publication_date`, `category_id`, `abstract`, `full_text_url`) VALUES
(1, 'Cloud-based Weather Condition Monitoring System using ESP8266 and Amazon Web Services', '8th International Conference On Information Technology Research (ICITR 2023) - (Scopus-indexed, IEEE)', '2023-02-08', 2, NULL, NULL),
(2, 'Smart Dustbin and Garbage Monitoring System using Internet of Things', '5th International Conference on Advancements in Computing (ICAC 2023) - (Scopus-indexed, IEEE)', '2023-12-07', 2, NULL, NULL),
(3, 'Genetic Sequencing of Native Sri Lankan Flora', 'International Symposium on Biodiversity (ISB 2024)', '2024-03-15', 1, NULL, NULL),
(4, 'Agile Project Management Techniques in the Tech Industry by wihanga', 'Journal of Modern Management, Vol. 18, Issue 2', '2023-11-20', 3, '0', ''),
(5, 'AI-driven Predictive Analytics in Healthcare', 'Global Health & Technology Conference (GHTC 2024)', '2024-01-29', 1, NULL, NULL),
(6, 'Test Research 1', 'sdsd', '2025-10-15', 1, '0', 'uploads/publications/1760680534_CD_720.pdf');

-- --------------------------------------------------------

--
-- Table structure for table `publication_authors`
--

CREATE TABLE `publication_authors` (
  `publication_id` int(11) NOT NULL,
  `author_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `publication_authors`
--

INSERT INTO `publication_authors` (`publication_id`, `author_id`) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 3),
(2, 4),
(2, 5),
(3, 6),
(3, 7),
(4, 3),
(4, 8),
(5, 9),
(5, 10),
(6, 3),
(6, 6),
(6, 9);

-- --------------------------------------------------------

--
-- Table structure for table `results`
--

CREATE TABLE `results` (
  `result_id` int(11) NOT NULL,
  `exam_title` varchar(255) NOT NULL,
  `exam_session` varchar(100) DEFAULT NULL COMMENT 'e.g., 2024-2025',
  `exam_type` varchar(100) DEFAULT NULL COMMENT 'e.g., Mid Term, Final',
  `subject_code` varchar(50) DEFAULT NULL,
  `upload_date` date NOT NULL,
  `file_path` varchar(255) NOT NULL COMMENT 'Path to the uploaded PDF/file',
  `created_by_cid` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1 COMMENT '1 for active (visible), 0 for inactive',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `reviews`
--

CREATE TABLE `reviews` (
  `id` int(11) NOT NULL,
  `item_id` varchar(255) DEFAULT NULL COMMENT 'Optional: Link to a specific item if reviewing products/courses',
  `user_name` varchar(100) NOT NULL,
  `rating` int(11) NOT NULL,
  `review_text` text NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `approved` tinyint(1) DEFAULT 0 COMMENT '0: Pending, 1: Approved (for moderation)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `reviews`
--

INSERT INTO `reviews` (`id`, `item_id`, `user_name`, `rating`, `review_text`, `created_at`, `approved`) VALUES
(1, 'general', 'Anuradha Perera', 5, 'This website offers a clean and straightforward design, making it easy to find information. The navigation is intuitive, and the content is well-organized. While the visual design is simple, its focus on functionality and speed is a huge plus. It provides essential information clearly and effectively. A great resource for its intended audience.', '2025-10-24 09:56:28', 1),
(2, 'general', 'Binuka Sanyuru', 5, 'Clean, fast, and easy to use! This website does exactly what it needs to without any unnecessary clutter. Finding information was a breeze. Highly recommended for its simplicity and efficiency.', '2025-10-24 09:57:15', 1);

-- --------------------------------------------------------

--
-- Table structure for table `slider`
--

CREATE TABLE `slider` (
  `sid` int(11) NOT NULL,
  `stitle` varchar(255) NOT NULL,
  `stext` longtext NOT NULL,
  `simg` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `status` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `slider`
--

INSERT INTO `slider` (`sid`, `stitle`, `stext`, `simg`, `created_at`, `updated_at`, `updated_by`, `status`) VALUES
(1, 'Learn. Grow. Succeed', '<p><span style=\"font-size: 14pt;\">Join the Advanced Technological Institute in Galle. </span></p>', 'uploads/sliders/1760415903_tumbnail.jpg', '2025-10-13 23:30:18', '2025-10-24 05:50:20', 'vihanga', 0),
(2, 'Your Future Starts Now', '<p>Applications for the new academic year are now open. Take the first step towards your dream career and apply today!</p>', 'uploads/sliders/1760957450_s-02.jpg', '2025-10-20 06:50:53', '2025-10-20 06:57:07', 'vihanga', 1),
(3, 'Welcome to ATI Galle', '<p>Your journey towards academic excellence and a vibrant student life begins here. Join our community of innovators and leaders.</p>', 'uploads/sliders/1760957541_s-4.jpg', '2025-10-20 06:52:21', '2025-10-20 06:52:21', 'vihanga', 1),
(4, 'Unlock Your Professional Future', '<p>Gain the practical skills and theoretical knowledge needed to thrive in today\'s competitive job market.</p>', 'uploads/sliders/1760957637_s-3.jpg', '2025-10-20 06:53:57', '2025-10-20 06:53:57', 'vihanga', 1),
(5, 'Begin Your Academic Journey', '<p>Admissions are now open. Apply today and take the next step in your educational and professional development.&nbsp;</p>', 'uploads/sliders/1760957681_s-06.jpg', '2025-10-20 06:54:41', '2025-10-20 07:00:09', 'vihanga', 1);

-- --------------------------------------------------------

--
-- Table structure for table `staff`
--

CREATE TABLE `staff` (
  `stid` int(11) NOT NULL,
  `sname` varchar(255) NOT NULL,
  `spos` varchar(255) NOT NULL,
  `cid` varchar(50) DEFAULT NULL,
  `sed` varchar(255) NOT NULL,
  `status` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  `stimg` varchar(255) NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `staff`
--

INSERT INTO `staff` (`stid`, `sname`, `spos`, `cid`, `sed`, `status`, `created_at`, `stimg`, `updated_at`) VALUES
(1, 'Mr.M.I.N.K Darmadasa', 'Lect', 'HND_ENGLISH', '', 1, '2025-10-14 02:36:26', 'uploads/staff/staff_68f453d02d15e2.45142061.jpg', '2025-10-19 03:50:54'),
(2, 'Mr. D.R.B.K.K Weerasekara', 'HOD', 'HNDME', '', 1, '2025-10-14 02:47:12', 'uploads/staff/staff_68f34d4653a421.62887739.jpg', '2025-10-18 04:18:14'),
(3, 'Ms. K.H.D Shehasini', 'HOD', 'HNDCE', '', 1, '2025-10-14 02:52:11', 'uploads/staff/staff_68f34d12c2ffb8.15686164.png', '2025-10-18 04:17:22'),
(4, 'Mrs. S.A.N.E Kumudu', 'Lect', 'HNDCE', '', 1, '2025-10-14 03:10:53', 'uploads/staff/staff_68f34cf3a475f9.44292187.png', '2025-10-18 04:16:51'),
(5, 'Mr. D.P Kalanasooriya', 'Lect', 'HNDCE', '', 1, '2025-10-14 03:11:55', 'uploads/staff/staff_68f34cd88a6871.76057588.png', '2025-10-18 04:16:24'),
(6, 'Mrs.Dammika Liyanage', 'Lect', 'HND_ENGLISH', '', 1, '2025-10-14 03:12:33', 'uploads/staff/staff_68f34cbcdd08f9.22749814.png', '2025-10-19 03:33:43'),
(7, 'Mr. N.H. De Silva Manawadu', 'Demo', 'HNDIT', '', 1, '2025-10-14 03:13:34', 'uploads/staff/staff_68f34c9f126661.64217058.png', '2025-10-19 04:07:21'),
(8, 'Mr. Wijesinghe', 'Lib', '', '', 1, '2025-10-14 03:32:21', 'uploads/staff/staff_68f34c8912ebc5.23170409.png', '2025-10-19 03:47:07'),
(9, 'D.M.T.P Fernando', 'Lect', 'HNDCE', '', 1, '2025-10-14 03:32:59', 'uploads/staff/staff_68f34c77114464.31774451.png', '2025-10-18 04:14:47'),
(10, 'Mrs. Chandrani Tennakoon', 'Lect', 'HNDCE', '', 1, '2025-10-14 03:33:41', 'uploads/staff/staff_68f34c5f634ae7.22920637.png', '2025-10-18 04:14:23'),
(11, 'Mrs. K.K.J Chandima', 'HOD', 'HNDIT', '', 1, '2025-10-14 04:21:52', 'uploads/staff/staff_68f34c4a1ee112.47611476.png', '2025-10-19 03:38:35'),
(12, 'Mr.P.H.M.P De Silva', 'Demo', 'HNDME', '', 1, '2025-10-14 04:23:10', 'uploads/staff/staff_68f34c346564f7.70031223.png', '2025-10-18 22:39:26'),
(13, 'Mrs. Y.R.A Prasadi', 'HOD', 'HNDME', '', 1, '2025-10-14 04:23:45', 'uploads/staff/staff_68f21aa1861e45.24046598.png', '2025-10-18 22:39:06'),
(14, 'Mr M.W Wadumulla', 'SLect', 'HNDME', '', 1, '2025-10-14 04:25:19', 'uploads/staff/staff_68f21a8c219113.49294100.png', '2025-10-18 05:31:19'),
(15, 'Mrs. B.W. Wickramasinghe', 'SLect', 'HNDT', '', 1, '2025-10-14 04:31:26', 'uploads/staff/staff_68f28145ce2660.19488680.png', '2025-10-19 03:25:46'),
(16, 'Mrs.D.N. Aththanayaka', 'SLect', 'HNDIT', '', 1, '2025-10-24 05:01:01', '', '2025-10-24 05:01:01'),
(17, 'Mr.M.U.C.T. Samarasekara', 'SLect', 'HNDIT', 'test', 1, '2025-10-24 05:01:27', '', '2025-10-24 05:18:50'),
(18, 'Mr.M.U.C.T. Samarasekara', 'SLect', 'HNDIT', '', 1, '2025-10-24 05:05:17', '', '2025-10-24 05:05:17');

-- --------------------------------------------------------

--
-- Table structure for table `tenders`
--

CREATE TABLE `tenders` (
  `tender_id` int(11) NOT NULL,
  `reference_no` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `published_date` date NOT NULL,
  `closing_date` datetime NOT NULL,
  `document_path` varchar(255) DEFAULT NULL,
  `status` enum('Open','Closed','Awarded','Cancelled') NOT NULL DEFAULT 'Open',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `university_announcements`
--

CREATE TABLE `university_announcements` (
  `announcement_id` varchar(125) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `target_audience` varchar(100) DEFAULT 'all',
  `priority` int(11) DEFAULT 0,
  `publish_datetime` datetime DEFAULT NULL,
  `expiry_datetime` datetime DEFAULT NULL,
  `status` int(11) DEFAULT 0 COMMENT '0=Draft/Inactive, 1=Published/Active, 2=Pending Review',
  `view_count` int(11) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `university_announcements`
--

INSERT INTO `university_announcements` (`announcement_id`, `title`, `content`, `image_path`, `target_audience`, `priority`, `publish_datetime`, `expiry_datetime`, `status`, `view_count`, `created_at`, `updated_at`) VALUES
('ANN_68EDC6F9EB898', 'UPDATES', '<p>A new leader is charting the course for innovation.</p>\r\n<p>We are thrilled to introduce Mr. Thamra Waidyarathna as the newly appointed Director of the Advanced Technological Institute, Labuduwa!</p>\r\n<p>This is more than a leadership change&mdash;it\'s an upgrade to our commitment to excellence. Get ready for accelerated growth,<strong> </strong>enhanced facilities, and a renewed focus on making our graduates the most sought-after professionals in the industry.</p>\r\n<p>The journey to the future of technology and education starts now.</p>', '', 'all', 0, '2025-10-02 09:11:00', '2025-10-31 09:11:00', 1, 0, '2025-10-14 03:43:53', '2025-10-24 09:52:50');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('super_admin','sub_admin') NOT NULL DEFAULT 'sub_admin',
  `cid` varchar(12) DEFAULT NULL,
  `profile_image` varchar(255) DEFAULT NULL,
  `pet_name_hint` varchar(100) DEFAULT NULL,
  `childhood_nickname_hint` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `status` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `role`, `cid`, `profile_image`, `pet_name_hint`, `childhood_nickname_hint`, `created_at`, `status`) VALUES
(1, 'Super Admin', '$2y$10$qdNL3J/F2d4La0lAiwE28.Qy.j5igG9SfecqPmyFX0UzINB3w2A1C', 'sub_admin', NULL, 'uploads/profile_images/user_681f340a5b08d5.10968859.jpg', 'priyantha', 'batta', '2025-05-10 16:40:02', 1),
(4, 'mano', '$2y$10$ZNFkGcHYe8P8hA1ua/KclerTXqZpAg2Wpn3bg/AQwjJEttPlOqZR.', 'sub_admin', NULL, 'uploads/user_68248721499381.20977841.jpg', 'q', 'q', '2025-05-14 17:35:53', 1),
(7, 'Super_Admin', '$2y$10$uvfZeEhDmlvIT0bfiY9OQeXqHPx8U.KYXb7nL.qD2ZmZUxRp7aKQK', 'sub_admin', NULL, NULL, 'priyantha', 'batta', '2025-10-05 11:24:28', 1),
(8, 'mano12', '$2y$10$/4O4LRfzRp0A2EMPhcBniuuFIf5hg/4P.zK75SwSXDVqMsW7qi6hO', 'sub_admin', 'HNDA', NULL, 'wet', 'wet', '2025-10-07 23:58:51', 1),
(9, 'mano13', '$2y$10$oUQOMANupEmX.m4FHtPrre.S.IJ6fytkz67WtyO4BR1ka0S9cVPm6', 'sub_admin', 'HNDQS', NULL, 'wet', 'wet', '2025-10-08 00:10:52', 1),
(10, 'super123', '$2y$10$h4zzv1CpEe1xk1CVDAv13eVZKXbqko0RaKoKchVnRqQk.xy.SCFFK', 'super_admin', NULL, NULL, 'wet', 'wet', '2025-10-08 00:39:48', 1),
(11, 'vihanga', '$2y$10$u72sh3Cz.IZ0p7KrldI7cuLdge5pUa314Squzv6pX44MlfxZdr8d2', 'super_admin', 'SAdmin', 'uploads/profile_images/user_11_68eb26c3844f73.52681293.jpg', 'wet', 'wet', '2025-10-12 08:55:34', 1),
(13, 'mano14', '$2y$10$92gLcd9IVOm5oUdn1l8zgu9zDYHkJR2C.VnVTCjE2wRbbTT/0qJtW', 'sub_admin', 'HNDA', NULL, 'wet', 'wet', '2025-10-17 03:25:54', 1),
(14, 'yashodhara1', '$2y$10$cX.NZ/ZLo1BmLELeXjKrCOPQIDRv0MeLOLCSB.hCYT4TafQykLVQW', 'super_admin', 'SAdmin', NULL, 'yash', 'yashr', '2025-10-17 05:32:06', 1),
(15, 'nipuni', '$2y$10$dCr42gJilBpLu0fFOdwHT..yDcQ.kEl78ZKrwX4w2Is6lkg9O.z9W', 'super_admin', 'SAdmin', NULL, 'nipuni', 'nipuni', '2025-10-18 04:22:52', 1);

-- --------------------------------------------------------

--
-- Table structure for table `user_device_logs`
--

CREATE TABLE `user_device_logs` (
  `id` int(11) NOT NULL,
  `user_cid` varchar(50) DEFAULT NULL,
  `log_time` timestamp NOT NULL DEFAULT current_timestamp(),
  `device_type` varchar(50) DEFAULT NULL,
  `device_vendor` varchar(50) DEFAULT NULL,
  `os` varchar(50) DEFAULT NULL,
  `browser` varchar(50) DEFAULT NULL,
  `screen_resolution` varchar(20) DEFAULT NULL,
  `timezone` varchar(100) DEFAULT NULL,
  `language` varchar(20) DEFAULT NULL,
  `latitude` varchar(50) DEFAULT NULL,
  `longitude` varchar(50) DEFAULT NULL,
  `battery_level` varchar(10) DEFAULT NULL,
  `connection_type` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user_device_logs`
--

INSERT INTO `user_device_logs` (`id`, `user_cid`, `log_time`, `device_type`, `device_vendor`, `os`, `browser`, `screen_resolution`, `timezone`, `language`, `latitude`, `longitude`, `battery_level`, `connection_type`) VALUES
(1, 'HNDA', '2025-10-18 08:00:33', 'desktop', 'unknown', 'Windows', 'Edge', '1536x864', 'Asia/Colombo', 'en-GB', NULL, NULL, '100%', '3g'),
(2, 'SAdmin', '2025-10-18 08:00:44', 'desktop', 'unknown', 'Windows', 'Chrome', '1680x1050', 'Asia/Colombo', 'en-US', '6.185804', '80.195625', '100%', 'unknown'),
(3, 'SAdmin', '2025-10-18 08:00:59', 'desktop', 'unknown', 'Windows', 'Chrome', '1680x1050', 'Asia/Colombo', 'en-US', '6.185804', '80.195625', '100%', 'unknown');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `about_page_content`
--
ALTER TABLE `about_page_content`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `albums`
--
ALTER TABLE `albums`
  ADD PRIMARY KEY (`AlbumId`);

--
-- Indexes for table `album_images`
--
ALTER TABLE `album_images`
  ADD PRIMARY KEY (`image_id`),
  ADD KEY `idx_albumid_images` (`AlbumId`);

--
-- Indexes for table `authors`
--
ALTER TABLE `authors`
  ADD PRIMARY KEY (`author_id`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`category_id`);

--
-- Indexes for table `choose_us_points`
--
ALTER TABLE `choose_us_points`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `course`
--
ALTER TABLE `course`
  ADD PRIMARY KEY (`cid`);

--
-- Indexes for table `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`eid`),
  ADD KEY `idx_albumid` (`AlbumId`);

--
-- Indexes for table `login_logs`
--
ALTER TABLE `login_logs`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_cid` (`user_cid`),
  ADD KEY `login_time` (`login_time`);

--
-- Indexes for table `modules`
--
ALTER TABLE `modules`
  ADD PRIMARY KEY (`module_code`),
  ADD KEY `cid` (`cid`);

--
-- Indexes for table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`nid`),
  ADD KEY `fk_news_department` (`cid`);

--
-- Indexes for table `notifications`
--
ALTER TABLE `notifications`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `publications`
--
ALTER TABLE `publications`
  ADD PRIMARY KEY (`publication_id`),
  ADD KEY `category_id` (`category_id`);

--
-- Indexes for table `publication_authors`
--
ALTER TABLE `publication_authors`
  ADD PRIMARY KEY (`publication_id`,`author_id`),
  ADD KEY `author_id` (`author_id`);

--
-- Indexes for table `results`
--
ALTER TABLE `results`
  ADD PRIMARY KEY (`result_id`);

--
-- Indexes for table `reviews`
--
ALTER TABLE `reviews`
  ADD PRIMARY KEY (`id`),
  ADD KEY `item_id` (`item_id`(250));

--
-- Indexes for table `slider`
--
ALTER TABLE `slider`
  ADD PRIMARY KEY (`sid`);

--
-- Indexes for table `staff`
--
ALTER TABLE `staff`
  ADD PRIMARY KEY (`stid`);

--
-- Indexes for table `tenders`
--
ALTER TABLE `tenders`
  ADD PRIMARY KEY (`tender_id`);

--
-- Indexes for table `university_announcements`
--
ALTER TABLE `university_announcements`
  ADD PRIMARY KEY (`announcement_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD KEY `fk_user_department` (`cid`);

--
-- Indexes for table `user_device_logs`
--
ALTER TABLE `user_device_logs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `album_images`
--
ALTER TABLE `album_images`
  MODIFY `image_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Auto-incrementing unique ID for each image entry', AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `authors`
--
ALTER TABLE `authors`
  MODIFY `author_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `category_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `choose_us_points`
--
ALTER TABLE `choose_us_points`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `login_logs`
--
ALTER TABLE `login_logs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT for table `news`
--
ALTER TABLE `news`
  MODIFY `nid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `notifications`
--
ALTER TABLE `notifications`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `password_resets`
--
ALTER TABLE `password_resets`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `publications`
--
ALTER TABLE `publications`
  MODIFY `publication_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `results`
--
ALTER TABLE `results`
  MODIFY `result_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `reviews`
--
ALTER TABLE `reviews`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `slider`
--
ALTER TABLE `slider`
  MODIFY `sid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `staff`
--
ALTER TABLE `staff`
  MODIFY `stid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- AUTO_INCREMENT for table `tenders`
--
ALTER TABLE `tenders`
  MODIFY `tender_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `user_device_logs`
--
ALTER TABLE `user_device_logs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `album_images`
--
ALTER TABLE `album_images`
  ADD CONSTRAINT `fk_albumimage_album` FOREIGN KEY (`AlbumId`) REFERENCES `albums` (`AlbumId`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `events`
--
ALTER TABLE `events`
  ADD CONSTRAINT `fk_event_album` FOREIGN KEY (`AlbumId`) REFERENCES `albums` (`AlbumId`) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Constraints for table `modules`
--
ALTER TABLE `modules`
  ADD CONSTRAINT `modules_ibfk_1` FOREIGN KEY (`cid`) REFERENCES `course` (`cid`);

--
-- Constraints for table `publications`
--
ALTER TABLE `publications`
  ADD CONSTRAINT `publications_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`) ON DELETE CASCADE;

--
-- Constraints for table `publication_authors`
--
ALTER TABLE `publication_authors`
  ADD CONSTRAINT `publication_authors_ibfk_1` FOREIGN KEY (`publication_id`) REFERENCES `publications` (`publication_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `publication_authors_ibfk_2` FOREIGN KEY (`author_id`) REFERENCES `authors` (`author_id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
