-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 27, 2025 at 01:19 AM
-- Server version: 8.2.0
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ati`
--

-- --------------------------------------------------------

--
-- Table structure for table `albums`
--

DROP TABLE IF EXISTS `albums`;
CREATE TABLE IF NOT EXISTS `albums` (
  `AlbumId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Unique Album ID, e.g., generated by uniqid("album_")',
  `album_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Name of the album, e.g., "Event XYZ Photos"',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp of album creation',
  PRIMARY KEY (`AlbumId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `albums`
--

INSERT INTO `albums` (`AlbumId`, `album_name`, `created_at`) VALUES
('album_6824fd3fd5416', '𝗜𝗡𝗧𝗥𝗢𝗩𝗔 𝟭.𝟬 - 𝗪𝗲𝗯 & 𝗥𝗼𝗯𝗼𝘁𝗶𝗰𝘀 𝗖𝗼𝗺𝗽𝗲𝘁𝗶𝘁𝗶𝗼𝗻 𝗢𝗿𝗴𝗮𝗻𝗶𝘇𝗲 𝗕𝘆 𝗣𝘂𝗹𝘇𝗮𝗿 𝗖𝗹𝘂𝗯 - 𝗦𝗟𝗜𝗔𝗧𝗘 𝗚𝗮𝗹𝗹𝗲 - 𝗗𝗲𝗽𝗮𝗿𝘁𝗺𝗲𝗻𝘁 𝗼𝗳 𝗜𝗻𝗳𝗼𝗿𝗺𝗮𝘁𝗶𝗼𝗻 𝗧𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝘆. Album', '2025-05-14 20:29:51'),
('album_6824fd7e6048f', 'ByteX Champions Album', '2025-05-14 20:30:54');

-- --------------------------------------------------------

--
-- Table structure for table `album_images`
--

DROP TABLE IF EXISTS `album_images`;
CREATE TABLE IF NOT EXISTS `album_images` (
  `image_id` int NOT NULL AUTO_INCREMENT COMMENT 'Auto-incrementing unique ID for each image entry',
  `AlbumId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Foreign key referencing the album this image belongs to',
  `image_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Path to the image file (e.g., uploads/albums/AlbumId/image.jpg)',
  `uploaded_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp of image upload',
  PRIMARY KEY (`image_id`),
  KEY `idx_albumid_images` (`AlbumId`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `album_images`
--

INSERT INTO `album_images` (`image_id`, `AlbumId`, `image_path`, `uploaded_at`) VALUES
(1, 'album_6824fd3fd5416', 'uploads/albums/album_6824fd3fd5416/1747254591_6824fd3fd9473_487306161_1181308230448965_6798907558379178198_n.jpg', '2025-05-14 20:29:51'),
(2, 'album_6824fd7e6048f', 'uploads/albums/album_6824fd7e6048f/1747254654_6824fd7e619f9_474322984_122186459042161373_7879874834701077398_n.jpg', '2025-05-14 20:30:54'),
(3, 'album_6824fd3fd5416', 'uploads/albums/album_6824fd3fd5416/1747288553_682581e90f346_about.png', '2025-05-15 05:55:53');

-- --------------------------------------------------------

--
-- Table structure for table `course`
--

DROP TABLE IF EXISTS `course`;
CREATE TABLE IF NOT EXISTS `course` (
  `cid` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ctext` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `cimg` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `status` int NOT NULL,
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`cid`, `cname`, `ctext`, `cimg`, `created_at`, `updated_at`, `status`) VALUES
('HNDBA', 'Higher National Diploma in Business Administration ', '<p>Sample text&nbsp; SAmple Text SAmple Text SAmple Text SAmple Text</p>', 'uploads/courses/1747253860_SLIIT-faculty-of-Business.jpg', '2025-05-15 01:37:30', '2025-05-15 01:47:40', 1),
('HNDE', 'Higher National Diploma in English', 'Higher National Diploma in English', 'uploads/courses/1747289680_SLIIT-faculty-of-Business.jpg', '2025-05-15 11:44:40', '2025-05-15 11:44:40', 1),
('HNDIT', 'Higher National Diploma in Information Technology', '<p data-sr-id=\"12\">HNDIT program at SLIATE is aimed to prepare students to&nbsp;</p>', 'uploads/courses/1747253870_SLIIT-faculty-of-Engineering-1.jpg', '2025-05-15 01:32:48', '2025-05-15 01:47:50', 1),
('HNDM', 'Higher National Diploma in Management', '<ul style=\"list-style-type: none;\">\r\n<li>\r\n<p>Management Management &nbsp;Management&nbsp;Management</p>\r\n</li>\r\n</ul>', 'uploads/courses/1747253850_SLIIT-Faculty-of-Graduate-Studies.jpg', '2025-05-15 01:43:58', '2025-05-15 01:47:30', 1);

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

DROP TABLE IF EXISTS `events`;
CREATE TABLE IF NOT EXISTS `events` (
  `eid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Event ID, as used in your PHP code (e.g., user-defined or unique string)',
  `etitle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Event Title',
  `etext` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Event Description, can store HTML content from TinyMCE',
  `etag` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'SEO Tags, comma-separated or other format',
  `AlbumId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Foreign key referencing the associated album in the albums table',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Event status: 1 for Active, 0 for Inactive',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp of event creation',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp of last event update',
  PRIMARY KEY (`eid`),
  KEY `idx_albumid` (`AlbumId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`eid`, `etitle`, `etext`, `etag`, `AlbumId`, `status`, `created_at`, `updated_at`) VALUES
('1', '𝗜𝗡𝗧𝗥𝗢𝗩𝗔 𝟭.𝟬 - 𝗪𝗲𝗯 & 𝗥𝗼𝗯𝗼𝘁𝗶𝗰𝘀 𝗖𝗼𝗺𝗽𝗲𝘁𝗶𝘁𝗶𝗼𝗻 𝗢𝗿𝗴𝗮𝗻𝗶𝘇𝗲 𝗕𝘆 𝗣𝘂𝗹𝘇𝗮𝗿 𝗖𝗹𝘂𝗯 - 𝗦𝗟𝗜𝗔𝗧𝗘 𝗚𝗮𝗹𝗹𝗲 - 𝗗𝗲𝗽𝗮𝗿𝘁𝗺𝗲𝗻𝘁 𝗼𝗳 𝗜𝗻𝗳𝗼𝗿𝗺𝗮𝘁𝗶𝗼𝗻 𝗧𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝘆.', '<div class=\"xdj266r x11i5rnm xat24cr x1mh8g0r x1vvkbs x126k92a\">\r\n<div dir=\"auto\"><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tde/1/16/1f4f8.png\" alt=\"📸\" width=\"16\" height=\"16\"></span> Unveiling Creativity and Innovation!</div>\r\n<div dir=\"auto\">Our campus exhibition brought ideas to life with groundbreaking projects in robotics creative websites , and thrilling games all developed by our talented batchmates.</div>\r\n</div>\r\n<div class=\"x11i5rnm xat24cr x1mh8g0r x1vvkbs xtlvy1s x126k92a\">\r\n<div dir=\"auto\">Adding to the excitement, we hosted an electrifying gaming competition, proudly sponsored by SellX Computers, Pvt. Ltd.</div>\r\n</div>\r\n<div class=\"x11i5rnm xat24cr x1mh8g0r x1vvkbs xtlvy1s x126k92a\">\r\n<div dir=\"auto\">Dive into the moments of innovation and competition through this photo album! Your support means the world. Let us know your favorite highlights in the comments! <span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t6e/1/16/1f4ac.png\" alt=\"💬\" width=\"16\" height=\"16\"></span></div>\r\n</div>', 'Introva, pulzar, Vihanga', 'album_6824fd3fd5416', 1, '2025-05-14 20:29:51', '2025-05-15 05:55:53'),
('2', 'ByteX Champions', '<div class=\"xdj266r x11i5rnm xat24cr x1mh8g0r x1vvkbs x126k92a\">\r\n<div dir=\"auto\"><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t50/1/16/1f525.png\" alt=\"🔥\" width=\"16\" height=\"16\"></span><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tbe/1/16/1f3c6.png\" alt=\"🏆\" width=\"16\" height=\"16\"></span> Congratulations, ByteX Champions! <span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tbe/1/16/1f3c6.png\" alt=\"🏆\" width=\"16\" height=\"16\"></span><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t50/1/16/1f525.png\" alt=\"🔥\" width=\"16\" height=\"16\"></span></div>\r\n</div>\r\n<div class=\"x11i5rnm xat24cr x1mh8g0r x1vvkbs xtlvy1s x126k92a\">\r\n<div dir=\"auto\">A massive shoutout to Keshan, Chamara, Siyath, and Shashika for dominating the COD tournament at ByteX during Introva 1.0! <span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t2f/1/16/1f3ae.png\" alt=\"🎮\" width=\"16\" height=\"16\"></span> Your incredible teamwork and skill secured a well-deserved victory. <span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t6c/1/16/1f4aa.png\" alt=\"💪\" width=\"16\" height=\"16\"></span><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tb0/1/16/1f3af.png\" alt=\"🎯\" width=\"16\" height=\"16\"></span></div>\r\n</div>\r\n<div class=\"x11i5rnm xat24cr x1mh8g0r x1vvkbs xtlvy1s x126k92a\">\r\n<div dir=\"auto\">Thank you to all participants for making this competition epic! Stay tuned for more action-packed events from Pulzar! <span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tc6/1/16/1f680.png\" alt=\"🚀\" width=\"16\" height=\"16\"></span></div>\r\n</div>\r\n<div class=\"x11i5rnm xat24cr x1mh8g0r x1vvkbs xtlvy1s x126k92a\">\r\n<div dir=\"auto\">We are The Pulzar Club <span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t0/1/16/1f5a4.png\" alt=\"🖤\" width=\"16\" height=\"16\"></span><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tf4/1/16/2728.png\" alt=\"✨\" width=\"16\" height=\"16\"></span></div>\r\n</div>', 'ByteX ,', 'album_6824fd7e6048f', 1, '2025-05-14 20:30:54', '2025-05-15 05:55:09');

-- --------------------------------------------------------

--
-- Table structure for table `modules`
--

DROP TABLE IF EXISTS `modules`;
CREATE TABLE IF NOT EXISTS `modules` (
  `module_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `module_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `module_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `credits` int DEFAULT NULL,
  `status` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `year` int DEFAULT NULL,
  `semester` int DEFAULT NULL,
  `cid` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`module_code`),
  KEY `cid` (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `modules`
--

INSERT INTO `modules` (`module_code`, `module_title`, `module_type`, `credits`, `status`, `year`, `semester`, `cid`) VALUES
('AGBM 1101', 'Introduction to Agribusiness Management', 'GPA', 3, '1', 1, 1, 'HNDBA'),
('AGBM 11011', 'Introduction to Agribusiness Management', 'GPA', 13, '1', 1, 1, 'HNDM');

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `nid` int NOT NULL AUTO_INCREMENT,
  `ntitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ntag` text COLLATE utf8mb4_unicode_ci,
  `ntext` text COLLATE utf8mb4_unicode_ci,
  `nimg` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `count` int DEFAULT '0',
  `status` tinyint DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`nid`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`nid`, `ntitle`, `ntag`, `ntext`, `nimg`, `count`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Introducing Our Amazing Web Team at Pulzar Club', 'pulzar, HNDIT, society', '<p>Introducing Our Amazing Web Team at Pulzar Club<br class=\"html-br\"><br class=\"html-br\">We are proud to present our talented Web Team at the Pulzar Club!&nbsp;<span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t8c/1/16/1f4bb.png\" alt=\"💻\" width=\"16\" height=\"16\"></span><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tf4/1/16/2728.png\" alt=\"✨\" width=\"16\" height=\"16\"></span>&nbsp;This dedicated group of innovators is working tirelessly to build and maintain our website, ensuring a seamless and engaging online experience for all. Their technical expertise and passion for technology are the foundation of our online platform, and we couldn&rsquo;t be more excited to see what&rsquo;s next!&nbsp;<span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tfd/1/16/1f64c.png\" alt=\"🙌\" width=\"16\" height=\"16\"></span></p>', 'uploads/news_images/1747254243_6824fbe35a4f0_474465458_122186715650161373_5376086591845834300_n.jpg', 3, 1, '2025-05-14 20:24:03', '2025-05-15 05:36:51'),
(2, 'Introducing Our Social Media Team at Pulzar Club', 'Pulzar, Hndit', '<p>Introducing Our Social Media Team at Pulzar Club<br class=\"html-br\"><br class=\"html-br\">We are excited to announce the launch of our dynamic Social Media Team at the Pulzar Club!&nbsp;<span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t8c/1/16/1f4bb.png\" alt=\"💻\" width=\"16\" height=\"16\"></span><span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t57/1/16/1f4f1.png\" alt=\"📱\" width=\"16\" height=\"16\"></span>&nbsp;This talented group of individuals is committed to bringing fresh, innovative content and engaging with our growing community. Their hard work and creativity are the driving forces behind our digital presence, and we couldn&rsquo;t be more proud!&nbsp;<span class=\"html-span xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs x3nfvp2 x1j61x8r x1fcty0u xdj266r xat24cr xgzva0m xhhsvwb xxymvpz xlup9mm x1kky2od\"><img class=\"xz74otr x168nmei x13lgxp2 x5pf9jr xo71vjh\" src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/tfd/1/16/1f64c.png\" alt=\"🙌\" width=\"16\" height=\"16\"></span></p>', 'uploads/news_images/1747254294_6824fc16f3fbe_473792482_122186714090161373_7397195164441078950_n.jpg', 1, 1, '2025-05-14 20:24:55', '2025-05-14 20:27:28'),
(3, '20th Convocation – Employability Survey Requirement', 'ATI Galle', '<p>All students who are&nbsp;<strong>eligible for the 20th Convocation</strong>&nbsp;from the following Advanced Technological Institutes (ATIs) are hereby informed that it is mandatory to complete the&nbsp;<strong>Employability Survey</strong>&nbsp;in order to collect your&nbsp;<strong>convocation cloak and garland.</strong></p>\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ATI List :-</p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Ampara</strong></p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Badulla</strong></p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Jaffna</strong></p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Nawalapitiya</strong></p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Mannar</strong></p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Sammanthurai</strong></p>\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Vavuniya</strong></p>\r\n<p><br>Eligible students from the listed ATIs are kindly requested to complete the survey using the link provided below:</p>', 'uploads/news_images/1747254439_6824fca75fd3c_8.jpg', 1, 1, '2025-05-14 20:27:19', '2025-05-14 20:27:30');

-- --------------------------------------------------------

--
-- Table structure for table `notifications`
--

DROP TABLE IF EXISTS `notifications`;
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'e.g., Slider, News, Event, Course, Announcement',
  `item_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The ID from the respective table (sid, nid, eid, cid, announcement_id)',
  `item_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Title or name of the item for easier display',
  `action` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'e.g., activated, deactivated',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the notification was created',
  `is_read` tinyint(1) DEFAULT '0' COMMENT 'Whether the notification has been viewed/marked as read (optional)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

DROP TABLE IF EXISTS `password_resets`;
CREATE TABLE IF NOT EXISTS `password_resets` (
  `id` int NOT NULL,
  `user_id` int NOT NULL,
  `token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expires_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `results`
--

DROP TABLE IF EXISTS `results`;
CREATE TABLE IF NOT EXISTS `results` (
  `result_id` int NOT NULL AUTO_INCREMENT,
  `exam_title` varchar(255) NOT NULL,
  `exam_session` varchar(100) DEFAULT NULL COMMENT 'e.g., 2024-2025',
  `exam_type` varchar(100) DEFAULT NULL COMMENT 'e.g., Mid Term, Final',
  `upload_date` date NOT NULL,
  `file_path` varchar(255) NOT NULL COMMENT 'Path to the uploaded PDF/file',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '1 for active (visible), 0 for inactive',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`result_id`)
) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `results`
--

INSERT INTO `results` (`result_id`, `exam_title`, `exam_session`, `exam_type`, `upload_date`, `file_path`, `is_active`, `created_at`, `updated_at`) VALUES
(6, 'Web Design', '2024 - 2025', '1st Semester', '2025-05-19', '682b0ece434d52.74357430_0027.pdf', 0, '2025-05-19 05:28:22', '2025-05-20 20:04:45'),
(8, 'ds', '2004-may', '2nd Semester', '2025-05-20', '682bfcaf3d9699.08589120_0027.pdf', 0, '2025-05-19 22:23:19', '2025-05-20 20:04:33');

-- --------------------------------------------------------

--
-- Table structure for table `reviews`
--

DROP TABLE IF EXISTS `reviews`;
CREATE TABLE IF NOT EXISTS `reviews` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` varchar(255) DEFAULT NULL COMMENT 'Optional: Link to a specific item if reviewing products/courses',
  `user_name` varchar(100) NOT NULL,
  `rating` int NOT NULL,
  `review_text` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `approved` tinyint(1) DEFAULT '0' COMMENT '0: Pending, 1: Approved (for moderation)',
  PRIMARY KEY (`id`),
  KEY `item_id` (`item_id`(250))
) ENGINE=MyISAM AUTO_INCREMENT=458 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `reviews`
--

INSERT INTO `reviews` (`id`, `item_id`, `user_name`, `rating`, `review_text`, `created_at`, `approved`) VALUES
(455, 'general', 'Vihanga', 5, 'Good', '2025-05-15 05:33:57', 1),
(456, 'general', 'devmi', 4, 'good', '2025-05-15 05:52:49', 1),
(457, 'general', 'Vihanga', 5, 'twest', '2025-09-27 01:15:27', 0);

-- --------------------------------------------------------

--
-- Table structure for table `slider`
--

DROP TABLE IF EXISTS `slider`;
CREATE TABLE IF NOT EXISTS `slider` (
  `sid` int NOT NULL AUTO_INCREMENT,
  `stitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stext` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `simg` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `status` int NOT NULL,
  PRIMARY KEY (`sid`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `slider`
--

INSERT INTO `slider` (`sid`, `stitle`, `stext`, `simg`, `created_at`, `updated_at`, `status`) VALUES
(1, 'Our Vision', '<p>\"At SLIATE, we empower you to explore, discover, and transform the world.\"&nbsp;</p>', 'uploads/sliders/1747252400_s-05.jpg', '2025-05-15 01:22:19', '2025-05-15 01:23:51', 1),
(2, 'Sample Title', '<p>\"Ignite your potential. Unlock your future. SLIATE.\"</p>', 'uploads/sliders/1747252490_s-2.jpg', '2025-05-15 01:24:50', '2025-05-15 01:29:34', 1),
(3, 'Sample Title', '', 'uploads/sliders/1747654236_360_F_85631184_nn8CvFT4qgIMOcp5ygFHFbO9y2kOTfq7.jpg', '2025-05-15 01:28:32', '2025-05-19 17:00:36', 1);

-- --------------------------------------------------------

--
-- Table structure for table `staff`
--

DROP TABLE IF EXISTS `staff`;
CREATE TABLE IF NOT EXISTS `staff` (
  `stid` int NOT NULL AUTO_INCREMENT,
  `sname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `spos` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sed` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` int NOT NULL,
  `created_at` datetime NOT NULL,
  `stimg` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`stid`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `staff`
--

INSERT INTO `staff` (`stid`, `sname`, `spos`, `sed`, `status`, `created_at`, `stimg`, `updated_at`) VALUES
(1, 'S.Ramanayake', 'Dire', '', 1, '2025-05-15 01:48:45', 'uploads/staff/1747253924_images.png', '2025-05-15 01:48:45'),
(2, 'Mr.S.P. Vithanage', 'Regi', '', 1, '2025-05-15 01:49:54', 'uploads/staff/1747253994_hndit2.webp', '2025-05-15 01:49:54'),
(3, 'Mr.K.M.G.T.R. Waidyarathne', 'HOD', '', 1, '2025-05-15 01:50:44', 'uploads/staff/1747254044_images.png', '2025-05-15 01:50:44'),
(4, 'Mrs.K.K.J. Chandima', 'SLect', '', 1, '2025-05-15 01:51:06', 'uploads/staff/1747254066_images.png', '2025-05-15 01:51:06');

-- --------------------------------------------------------

--
-- Table structure for table `university_announcements`
--

DROP TABLE IF EXISTS `university_announcements`;
CREATE TABLE IF NOT EXISTS `university_announcements` (
  `announcement_id` varchar(125) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_audience` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT 'all',
  `priority` int DEFAULT '0',
  `publish_datetime` datetime DEFAULT NULL,
  `expiry_datetime` datetime DEFAULT NULL,
  `status` int NOT NULL DEFAULT '0',
  `view_count` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`announcement_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `university_announcements`
--

INSERT INTO `university_announcements` (`announcement_id`, `title`, `content`, `image_path`, `target_audience`, `priority`, `publish_datetime`, `expiry_datetime`, `status`, `view_count`, `created_at`, `updated_at`) VALUES
('ANNCOO1', 'test announcement', '<p>student registation is <strong>now </strong>open</p>', 'uploads/announcement_images/1747288857_682583192cc30_SLIIT-Faculty-of-Graduate-Studies.jpg', 'students', 1, '2025-05-16 11:30:00', '2029-06-21 11:30:00', 1, 0, '2025-05-15 06:00:57', '2025-09-27 01:14:57');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `profile_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pet_name_hint` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `childhood_nickname_hint` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `status` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `profile_image`, `pet_name_hint`, `childhood_nickname_hint`, `created_at`, `status`) VALUES
(1, 'Super Admin', '$2y$10$qdNL3J/F2d4La0lAiwE28.Qy.j5igG9SfecqPmyFX0UzINB3w2A1C', 'uploads/profile_images/user_681f340a5b08d5.10968859.jpg', 'priyantha', 'batta', '2025-05-10 16:40:02', 1),
(2, 'rane', '$2y$10$7QIdOlKBQE9edDxHY4KOveUHxInlHjHNNpi1/tRY7vN8bfUZheEdm', 'uploads/user_6824d12ef18155.80531212.png', 'priyantha', 'batta', '2025-05-10 17:01:07', 0),
(3, 'sano', '$2y$10$NgaTjVGcmfck7utk5MOfB.rPFdVyYCJpOlaaqYrhCCyuHLWzObO4G', 'uploads/profile_images/user_682473ff270b92.13520052.jpg', 'priyantha', 'batta', '2025-05-14 16:14:15', 1),
(4, 'mano', '$2y$10$ZNFkGcHYe8P8hA1ua/KclerTXqZpAg2Wpn3bg/AQwjJEttPlOqZR.', 'uploads/user_68248721499381.20977841.jpg', 'priyantha', 'batta', '2025-05-14 17:35:53', 1),
(5, 'manowe', '$2y$10$WmcQTaD/wHz/bMFViIEiveHliZZm0IvVtt8v9M/ZIaLd9VicTDgee', 'uploads/profile_images/user_68d73974465195.81763594.png', 'wet', 'wet', '2025-09-27 06:40:12', 1);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `album_images`
--
ALTER TABLE `album_images`
  ADD CONSTRAINT `fk_albumimage_album` FOREIGN KEY (`AlbumId`) REFERENCES `albums` (`AlbumId`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `events`
--
ALTER TABLE `events`
  ADD CONSTRAINT `fk_event_album` FOREIGN KEY (`AlbumId`) REFERENCES `albums` (`AlbumId`) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Constraints for table `modules`
--
ALTER TABLE `modules`
  ADD CONSTRAINT `modules_ibfk_1` FOREIGN KEY (`cid`) REFERENCES `course` (`cid`) ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
